/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroDeScript.java
 *
 * Created on 09/02/2015, 22:35:20
 */
package com.krismorte.zion.view;

import javax.swing.JOptionPane;
import com.krismorte.zion.model.Script;
import com.krismorte.zion.util.LimpaCampos;
import com.krismorte.zion.util.SQLDialect;
import com.krismorte.zion.view.util.EditorSQL;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author krismorte <krisnamourt_ti@hotmail.com>
 */
public class CadastroDeScript extends javax.swing.JDialog {

    private static Logger logger = LoggerFactory.getLogger(CadastroDeScript.class);
    /**
     * Creates new form CadastroDeScript
     */
    public CadastroDeScript(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencheBoxGrupo();
    }
    
    private void preencheBoxGrupo() {
        boxGrupo.removeAllItems();
        boxGrupo.addItem("");
        for (String s : Script.getListaDeGruposPorTipo(boxTipo.getSelectedItem().toString())) {
            boxGrupo.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        boxGrupo = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtScript = new EditorSQL(SQLDialect.getDialectMSSQL());
        jLabel4 = new javax.swing.JLabel();
        boxTipo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Scripts");

        jLabel1.setText("Nome do Script:");

        jLabel2.setText("Corpo do Script:");

        jButton1.setText("salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Grupo:");

        boxGrupo.setEditable(true);

        jScrollPane2.setViewportView(txtScript);

        jLabel4.setText("Tipo:");

        boxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MSSQL" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxTipo, 0, 146, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(boxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtNome.getText().equals("") || txtScript.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os valores sao obrigatorios");
        } else {
            String nomeArquivo = txtNome.getText();
            if (!nomeArquivo.endsWith(".sql")) {//adiciona extensão
                nomeArquivo += ".sql";
            }
            String grupo = "";
            if (!(boxGrupo.getSelectedItem().toString().equals(""))) {
                grupo = boxGrupo.getSelectedItem().toString().toUpperCase();
            }
            Script scr = new Script(nomeArquivo, boxTipo.getSelectedItem().toString(), grupo, txtScript.getText());
            if (scr.add()) {
                if (scr.criouTipo) {
                    preencheBoxGrupo();
                    //Main.logApp.addMsgLog(CadastroDeServidor.class.getCanonicalName(), "Novo Tipo de script " + scr.getTipo() + " adicionado com sucesso");
                    logger.info("Novo Tipo de script " + scr.getTipo() + " adicionado com sucesso");
                }
                JOptionPane.showMessageDialog(this, "Script cadastrado com Sucesso!");
                logger.info("Script " + txtNome.getText() + " adicionado com sucesso");
                LimpaCampos.limpaCampos(this);
            } else {
                JOptionPane.showMessageDialog(this, "Falha no cadastro do Script!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                CadastroDeScript dialog = new CadastroDeScript(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxGrupo;
    private javax.swing.JComboBox boxTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextPane txtScript;
    // End of variables declaration//GEN-END:variables
}
