/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krismorte <krisnamourt_ti@hotmail.com>
 */
package com.krismorte.zion.view.subpanels;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import com.krismorte.zion.util.Tabela;
import com.krismorte.zion.view.operationPanel;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author krismorte <krisnamourt_ti@hotmail.com>
 */
public class listScriptPanel extends scriptPanel {

    private ResourceBundle resourceBundle = ResourceBundle.getBundle("SystemMessages", Locale.getDefault());
    private String[] columns;
    private Object[][] rows;
    public static int initialValue;
    public static int sucessValue;
    public static int failValue;
    private List<File> files = new ArrayList<File>();

    /**
     * Creates new form panelScriptLivre
     */
    public listScriptPanel(operationPanel panel) {
        super(panel);
        initComponents();
        String[] colTMP = {resourceBundle.getString("ORDER"), resourceBundle.getString("STATUS")};
        columns = colTMP;
        refreshTable();
    }



   public String getParallelism() {
        return panel.getParallelism();
    }


 public void initCounter(int initialValue, int sucessValue, int failValue) {
        this.initialValue = initialValue;
        this.sucessValue = sucessValue;
        this.failValue = failValue;
        panel.setTotal("" + initialValue);
        panel.setWainting("" + initialValue);
        panel.setFail("" + failValue);
        panel.setSuccess("" + sucessValue);

    }

    public void updateSucessCounter() {
        sucessValue++;
        initialValue--;
        panel.setWainting("" + initialValue);
        panel.setSuccess("" + sucessValue);

    }

    public void updateFailCounter() {
        failValue++;
        initialValue--;
        panel.setWainting("" + initialValue);
        panel.setFail("" + failValue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtArquivo = new javax.swing.JTextField();
        panelResultados = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText(resourceBundle.getString("SCRIPT")+":");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelResultados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jButton2.setText(resourceBundle.getString("RM_FILES")+":");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        files.clear();
        refreshTable();
        txtArquivo.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JTextField txtArquivo;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        fulfilRows();
        Tabela.preencheTabela(panelResultados, columns, rows);
    }

    public void fulfilRows() {
        rows = new Object[files.size()][columns.length];
        if (files.size() > 0) {
            for (int i = 0; i < files.size(); i++) {
                for (int z = 0; z < columns.length; z++) {
                    Object[][] obj = {{i, files.get(i).getAbsoluteFile()}};
                    rows[i][z] = obj[0][z];//Rows are dynamics
                }
            }
        }
    }
}
