/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krismorte.zion.view.subpanels;

import com.krismorte.zion.model.ZionParameters;
import com.krismorte.zion.view.operationPanel;

/**
 *
 * @author krismorte <krisnamourt_ti@hotmail.com>
 */
public class scriptPanel extends javax.swing.JPanel{

    protected int initialValue;
    protected int sucessValue;
    protected int failValue;
    protected operationPanel panel;

    /**
     * Creates new form scriptPanel
     */
    public scriptPanel(operationPanel panel) {
        //initComponents();
        this.panel = panel;
        panel.setParallelism("" + ZionParameters.parallelism);
    }

    public boolean verificaParalelismo() {
        try {
            int par = Integer.parseInt(panel.getParallelism());
            return ZionParameters.isValidParallelismValue(par);
        } catch (NumberFormatException e) {
            panel.setParallelism("" + ZionParameters.parallelism);
            return false;
        }
    }

    public void initCounter(int initialValue, int sucessValue, int failValue) {
        this.initialValue = initialValue;
        this.sucessValue = sucessValue;
        this.failValue = failValue;
        panel.setTotal("" + initialValue);
        panel.setWainting("" + initialValue);
        panel.setFail("" + failValue);
        panel.setSuccess("" + sucessValue);
    }

    public void updateSucessCounter() {
        sucessValue++;
        initialValue--;
        panel.setWainting("" + initialValue);
        panel.setSuccess("" + sucessValue);
    }

    public void updateFailCounter() {
        failValue++;
        initialValue--;
        panel.setWainting("" + initialValue);
        panel.setFail("" + failValue);
    }

    public String getParallelism() {
        return panel.getParallelism();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
